[tool.poetry]
name = "tqdne"
version = "0.1.0"
readme = "README.rst"
description = ""
authors = ["Your Name <you@example.com>"]


[tool.poetry.dependencies]
python = "^3.11.3"
tqdm = "*"
scikit-learn = "*"
scikit-image = "*"
numpy = "*"
matplotlib = "*"
seaborn = "*"
python-dotenv = "*"
setuptools = "*"
wandb = "*"
torchvision = "*"
pytorch-lightning = ">=2.0.0"
h5py = "*"
diffusers = {path = "diffusers", extras = ["torch", "training"], develop = true}
accelerate = "*"
transformers = "*"
plotly = "*"
torch = "2.0.0"
seaborn = "^0.13.0"
mlflow = "^2.8.0"
torchsummary = "^1.5.1"



[tool.poetry.dev-dependencies]
pytest = "*"
jupyterlab = "*"
ipywidgets = "*"
twine = "*"
setuptools = "*"
wheel = "*"
flake8 = "*"
pylint = "*"
sphinx = "<7.0.0"
numpydoc = "*"
sphinxcontrib-bibtex = "*"
sphinx-gallery = "*"
memory_profiler = "*"
sphinx-rtd-theme = "*"
sphinx-copybutton = "*"
nbsphinx = "*"
pandoc = "*"
black = "*"

[tool.poetry.group.dev.dependencies]
notebook = "^6.5.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


