[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tqdne"
authors= [{name = "HighFEM team", email = "example@mail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
dependencies = [
    "diffusers>=0.26.3",
    "h5py>=3.10.0",
    "librosa>=0.10.2.post1",
    "pandas>=2.2.2",
    "pathos>=0.3.2",
    "pytorch-lightning>=2.1.3",
    "seaborn>=0.13.2",
    "scikit-image>=0.22.0",
    "scikit-learn>=1.4.0",
    "seisbench>=0.8.0",
    "torch>=2.2.0",
    "wandb>=0.19.7",
    "einops>=0.8.1",
]
dynamic = ["version"]

[tool.setuptools]
packages = ["tqdne"]

[tool.setuptools.dynamic]
version = {attr = "tqdne.__init__.__version__"}

[tool.bandit]
skips = ["B101"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = [
  "UP", "I", "PL", "S"
]
ignore = ["S301", "PLR0913", "S101", "PLR2004", "S603", "S607", "PLW2901", "E721", "S307", "PLR0915", "E741", "S110", "E722"]

[tool.uv]
dev-dependencies = [
    "pre-commit>=3.8.0",
    "ruff",
]
