[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "tqdne"
version = "0.1.0"
readme = "README.rst"
description = ""
requires-python = ">=3.11"
authors= [{name = "HighFEM team", email = "example@mail.com"}]
dependencies = [
    "python-dotenv>=1.0.1",
    "pytorch-lightning>=2.1.3",
    "scikit-image>=0.22.0",
    "scikit-learn>=1.4.0",
    "seaborn>=0.13.2",
    "torch>=2.2.0",
]

[tool.setuptools]
packages = ["tqdne"]


[tool.flake8]
max-line-length = 100
per-file-ignores = [
    '__init__.py:F401',
]

[tool.black]
line-length = 100
target-version = ['py39']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''