[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "tqdne"
version = "0.1.0"
readme = "README.rst"
description = ""
requires-python = ">=3.11"
authors= [{name = "HighFEM team", email = "example@mail.com"}]

[tool.setuptools]
packages = ["tqdne"]