name: tqdne
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - h5py=3.10.0
  - jupyterlab=4.1.1
  - jupytext=1.16.1
  - matplotlib=3.8.2
  - diffusers=0.26.3
  - python=3.11.7
  - python-dotenv=1.0.1
  - pytorch=2.2.0
  - pytorch-lightning=2.1.3
  - scikit-image=0.22.0
  - scikit-learn=1.4.0
  - seaborn=0.13.2
  - librosa=0.10.1
  - wandb=0.16.3
  - pathos=0.3.2
  - pandas=2.2.2
  - obspy=1.4.1
  - pip
  - pip:
      - einops==0.8.1
      - plotly==5.20.0
      - seisbench==0.8.0      
      - -e .
