name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format_and_check:
    name: Format & Pre-commit checks
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install ruff
      - name: Run ruff
        run: ruff format . --exclude '*.ipynb'
      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: autoformat code with ruff [skip ci]"
          branch: ${{ github.ref_name }}
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
